[tool.pyflow]
name = "prosessilouhinta"
py_version = "3.8"
version = "2021.11.27"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
